CREATE TABLE project_info (
    id TEXT PRIMARY KEY,
    state TEXT,
    utility TEXT,
    region TEXT,
    mwh_savings FLOAT,
    therms_savings FLOAT,
    load_shape TEXT,
    therms_profile TEXT,
    start_year INTEGER,
    start_quarter INTEGER,
    start_date TEXT,
    end_date TEXT,
    units INTEGER,
    eul INTEGER,
    ntg FLOAT,
    discount_rate FLOAT,
    admin_cost FLOAT,
    measure_cost FLOAT,
    incentive_cost FLOAT,
    value_curve_name TEXT
);