FROM python:3.9.1

RUN apt-get update\
    && apt-get install -y --no-install-recommends graphviz

RUN apt-get install -y sqlite3
RUN pip install --upgrade pip==21.0.1

COPY requirements.txt ./
RUN pip install -r requirements.txt

COPY setup.py README.rst /app/
COPY flexvalue/ /app/flexvalue/

WORKDIR /app
ENV PYTHONPATH=/app

RUN cd /usr/local/lib/ && python /app/setup.py develop
